Repository perfolio/web, pull requests merged in 2020-08, with the labels that each got.

#132 Only test against node v14
  .github/workflows/ci.yml
  nx.json
Labels: merge

#143 Update nx cloud cache token
  nx.json
Labels: Patch Version, merge

#145 Fix/index size
  packages/components/src/layout/section/__snapshots__/section.spec.tsx.snap
  packages/components/src/layout/section/section.tsx
  packages/core/pages/_app.tsx
  packages/core/pages/index.tsx
  packages/core/specs/__snapshots__/index.spec.tsx.snap
Labels: Patch Version, bugfix, merge

#144 Feature/mobile menu
  packages/components/src/navigation/desktop/desktop.spec.tsx
  packages/components/src/navigation/desktop/desktop.tsx
  packages/components/src/navigation/mobile/mobile.spec.tsx
  packages/components/src/navigation/mobile/mobile.tsx
  packages/components/src/navigation/navbar/__snapshots__/navbar.spec.tsx.snap
  packages/components/src/navigation/navbar/navbar.spec.tsx
  packages/components/src/navigation/navbar/navbar.tsx
  packages/core/pages/_app.tsx
  packages/research/pages/_app.tsx
Labels: Patch Version, merge

#151 Refactor/convert charts to library
  nx.json
  package.json
  packages/charts/.babelrc
  packages/charts/.eslintrc
  packages/charts/README.md
  packages/charts/babel-jest.config.json
  packages/charts/jest.config.js
  packages/charts/src/index.ts
  packages/charts/src/line/__snapshots__/line.spec.tsx.snap
  packages/charts/src/line/line.spec.tsx
  packages/charts/src/line/line.tsx
  packages/charts/tsconfig.json
  packages/charts/tsconfig.lib.json
  packages/charts/tsconfig.spec.json
  packages/components/src/index.ts
  packages/components/src/layout/footer/footer.tsx
  packages/components/src/lib/components.tsx
  packages/components/src/lib/scroll-tip/scroll-tip.spec.tsx
  packages/components/src/lib/scroll-tip/scroll-tip.tsx
  packages/components/src/navigation/mobile/mobile.tsx
  packages/research/pages/_app.tsx
  packages/research/pages/index.tsx
  packages/research/specs/__snapshots__/index.spec.tsx.snap
  tsconfig.base.json
  workspace.json
Labels: merge, refactor

#157 Feature/research index page
  packages/components/src/index.ts
  packages/components/src/lib/source/__snapshots__/source.spec.tsx.snap
  packages/components/src/lib/source/source.spec.tsx
  packages/components/src/lib/source/source.tsx
  packages/research/pages/index.tsx
  packages/research/specs/__snapshots__/index.spec.tsx.snap
Labels: Minor Version, enhancement, merge

#158 Feature/make research mobile friendly
  package.json
  packages/components/src/index.ts
  packages/components/src/layout/footer/__snapshots__/footer.spec.tsx.snap
  packages/components/src/layout/footer/footer.tsx
  packages/components/src/layout/section/__snapshots__/section.spec.tsx.snap
  packages/components/src/layout/section/section.tsx
  packages/components/src/layout/section/title/section-title.spec.tsx
  packages/components/src/layout/section/title/section-title.tsx
  packages/components/src/lib/source/__snapshots__/source.spec.tsx.snap
  packages/components/src/lib/source/source.spec.tsx
  packages/components/src/lib/source/source.tsx
  packages/core/specs/__snapshots__/index.spec.tsx.snap
  packages/research/pages/index.tsx
  packages/research/public/sources/SnP-nico.md
  packages/research/public/sources/kenneth-french.md
  packages/research/specs/__snapshots__/index.spec.tsx.snap
  packages/research/specs/index.spec.tsx
  yarn.lock
Labels: enhancement, merge

#168 Update release-drafter.yml
  .github/workflows/release-drafter.yml
Labels: merge

#187 Add all feature bullet points
  packages/core/pages/index.tsx
  packages/core/specs/__snapshots__/index.spec.tsx.snap
Labels: enhancement, merge

#190 Finish team section and refactor some components
  packages/components/src/index.ts
  packages/components/src/lib/feature/feature.spec.tsx
  packages/components/src/lib/feature/feature.tsx
  packages/components/src/lib/profile/profile.spec.tsx
  packages/components/src/lib/profile/profile.tsx
  packages/core/pages/index.tsx
  packages/core/public/img/andreas.jpeg
  packages/core/public/img/andreas_bw.jpeg
  packages/core/public/img/kevin.jpeg
  packages/core/public/img/kevin_bw.jpeg
  packages/core/public/img/mads.jpeg
  packages/core/public/img/mads_bw.jpeg
  packages/core/public/img/nico.jpeg
  packages/core/public/img/nico_bw.jpeg
  packages/core/specs/__snapshots__/index.spec.tsx.snap
Labels: core, enhancement, merge

#177 Add meta tags for core and research page
  packages/core/pages/_app.tsx
  packages/research/pages/_app.tsx
Labels: merge

#196 Add workflow
  .github/workflows/create-issue-branch.yml
Labels: merge

#191 Fix/navbar spacing
  package.json
  packages/components/src/navigation/navbar/__snapshots__/navbar.spec.tsx.snap
  packages/components/src/navigation/navbar/navbar.tsx
  packages/core/pages/_app.tsx
  packages/research/pages/_app.tsx
  yarn.lock
Labels: Patch Version, bugfix, core, merge, refactor, research

#198 Issue 195 add team text
  packages/components/src/lib/feature/feature.tsx
  packages/core/pages/index.tsx
  packages/core/specs/__snapshots__/index.spec.tsx.snap
Labels: core, enhancement, merge

#199 Add icons
  packages/core/pages/_app.tsx
  packages/core/public/fav/android-chrome-192x192.png
  packages/core/public/fav/android-chrome-512x512.png
  packages/core/public/fav/apple-touch-icon.png
  packages/core/public/fav/browserconfig.xml
  packages/core/public/fav/favicon-16x16.png
  packages/core/public/fav/favicon-32x32.png
  packages/core/public/fav/favicon.ico
  packages/core/public/fav/mstile-150x150.png
  packages/core/public/fav/safari-pinned-tab.svg
  packages/core/public/fav/site.webmanifest
  packages/core/public/img/logo.svg
  packages/research/pages/_app.tsx
  packages/research/public/fav/android-chrome-192x192.png
  packages/research/public/fav/android-chrome-512x512.png
  packages/research/public/fav/apple-touch-icon.png
  packages/research/public/fav/browserconfig.xml
  packages/research/public/fav/favicon-16x16.png
  packages/research/public/fav/favicon-32x32.png
  packages/research/public/fav/favicon.ico
  packages/research/public/fav/mstile-150x150.png
  packages/research/public/fav/safari-pinned-tab.svg
  packages/research/public/fav/site.webmanifest
Labels: core, enhancement, merge, research

#200 Remove <> from links
  packages/research/public/sources/SnP-nico.md
  packages/research/public/sources/kenneth-french.md
Labels: Minor Version, bug, bugfix, merge, research

#201 Fix/issue 182 fix font in chrome
  package.json
  packages/components/src/lib/scroll-tip/scroll-tip.tsx
  packages/core/pages/_app.tsx
  packages/core/pages/_document.tsx
  packages/core/pages/index.tsx
  packages/core/specs/__snapshots__/index.spec.tsx.snap
  packages/research/pages/_app.tsx
  packages/research/pages/_document.tsx
  packages/tailwindcss/tailwind.config.js
  workspace.json
  yarn.lock
Labels: bugfix, core, merge, research

#203 Feature/issue 193 sign up button should be a link to signup
  packages/components/src/layout/hero-section/__snapshots__/hero-section.spec.tsx.snap
  packages/components/src/layout/hero-section/hero-section.tsx
  packages/core/specs/__snapshots__/index.spec.tsx.snap
  packages/research/pages/index.tsx
  packages/research/specs/__snapshots__/index.spec.tsx.snap
Labels: bugfix, core, research

#208 Move outer styling outside of feature component
  packages/components/src/lib/feature/feature.tsx
  packages/core/pages/index.tsx
  packages/core/specs/__snapshots__/index.spec.tsx.snap
Labels: bugfix, core

#215 Upgrade to latest
  package.json
  yarn.lock
Labels: dependencies, merge

#217 Use shield icon for 'Privacy and Security'
  packages/core/pages/index.tsx
  packages/core/specs/__snapshots__/index.spec.tsx.snap
Labels: bugfix, core, merge

#221 Fix/perfolio logo in team section
  packages/core/pages/index.tsx
  packages/core/specs/__snapshots__/index.spec.tsx.snap
Labels: bugfix, core, merge

#222 Fix layout
  packages/core/pages/index.tsx
  packages/core/specs/__snapshots__/index.spec.tsx.snap
  packages/research/pages/index.tsx
  packages/research/specs/__snapshots__/index.spec.tsx.snap
Labels: bugfix, merge

#223 Explicitely wrap every page that requires navigation
  package.json
  packages/components/src/index.ts
  packages/components/src/lib/nav-wrapper/nav-wrapper.spec.tsx
  packages/components/src/lib/nav-wrapper/nav-wrapper.tsx
  packages/core/components/wrapper/wrapper.spec.tsx
  packages/core/components/wrapper/wrapper.tsx
  packages/core/pages/_app.tsx
  packages/core/pages/index.tsx
  packages/core/pages/subscribe/success.tsx
  packages/core/specs/__snapshots__/index.spec.tsx.snap
  packages/core/specs/subscription-success.spec.tsx
  packages/research/components/wrapper/wrapper.spec.tsx
  packages/research/components/wrapper/wrapper.tsx
  packages/research/pages/_app.tsx
  packages/research/pages/index.tsx
  packages/research/specs/__snapshots__/index.spec.tsx.snap
  yarn.lock
Labels: core, merge, refactor, research
